<html>
	<head>
        <title>A&O Nebenleistungen</title>
	</head>
	<body>
        <script type="text/javascript">
			location.href = "/front/login/";
		</script>

        <script type="text/javascript">
            
        </script>

        <noscript>
            <div style='margin: 50px auto; border: solid 1px blue; width: 400px; height: 200px; padding: 20px;'>
                Sehr geehrter Besucher unseres Onlineportals!<br><br>
                Bitte aktivieren Sie in Ihrem Browser die Verarbeitung von Javascript und rufen Sie diese Seite erneut auf.
            </div>
        </noscript>
	</body>
</html>
