<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=8" />
        <link rel="shortcut icon" href="favicon.ico">


		<link rel="stylesheet" type="text/css" href="/blueprint/grid.css" media="screen, projection">
		<link rel="stylesheet" type="text/css" href="/blueprint/print.css"  media="print">
		<!--[if lt IE 8]>
			<link rel="stylesheet" href="/blueprint/ie.css" type="text/css" media="screen, projection">
		<![endif]-->
		<link rel="stylesheet" type="text/css" href="/jquery_navigation/droppy.css">
		<link rel="stylesheet" type="text/css" href="/css/front.css">
		<link rel="stylesheet" type="text/css" href="/jquery_ui/css/humanity/jquery-ui.css">
		<link rel="stylesheet" href="/jquery_form_validation/css/validationEngine.jquery.css" type="text/css"/>

		<script type='text/javascript' src='/jquery/jquery.js'></script>
		<script type="text/javascript" src='/jquery_ui/js/jquery-ui.js'></script>

		<link rel="stylesheet" href="/jquery_form_validation/css/template.css" type="text/css"/>
		<script src="/jquery_form_validation/jquery.validationEngine-<?php echo Zend_Registry::get('language');  ?>.js" type="text/javascript" charset="utf-8"></script>
		<script src="/jquery_form_validation/jquery.validationEngine.js" type="text/javascript" charset="utf-8"></script>

		<script type="text/javascript" src='/jquery_spinner/ui.spinner.min.js'></script>

		<script src='/jquery_navigation/jquery.droppy.js' type='text/javascript'></script>

		<script type='text/javascript'>
			var language = '<?php echo Zend_Registry::get('language');  ?>';
			$(document).ready(function() {
				$('#nav').droppy();

			});
		</script>

		<title>Herden Studienreisen</title>

	</head>
	<body align='center'>
		<div id='main' class='showgrid'>
			<div class='span-8' id='logo'>
				Logo:
			</div>
			<div id='suche' class='span-8'>
				<form method='post' action='/front/programmsuche/'>
					Suchmaske: <input class='input-mittel' name='searchTerm' id='searchTerm'> <input type='image' src='/buttons/sound_add.png' name='suche'>
				</form>
			</div>
			<div id='login' class='span-7'>
				<form method='post' action='/front/login/index/'>
					<?php echo translate('Mail - Adresse'); ?>: <input type='text' class='input-mittel' name='username'><br>
					<?php echo translate('Passwort'); ?>: <input type='password' class='input-mittel' name='password'>
					<?php echo buttonLoginLogout(); ?>
				</form>
			</div>

			<div id='navigation' class='span-23' style="z-index: 3000;">
				<div class='span-8' style="z-index: 2000;">
					<ul id='nav' style="z-index: 1005;">
						<li><a href='/front/login/index/'>Home</a></li>
						<li><a href='#'><?php echo translate('Städte'); ?></a><?php echo $this->navigation()->menu(); ?></li>
						<li><a href="#"><?php echo translate('Service');?></a><?php echo nook_Tool::buildServiceArea(); ?></li>
						<li><a href='/front/warenkorb/index/'><?php echo translate('Warenkorb'); ?></a></li>
						<li><a href='#'><?php echo translate('Administration'); ?></a><?php echo nook_Tool::buildAdminArea(); ?></li>
					</ul>
				</div>
				<div id='breadcrumb' class='span-4'><?php echo $this->crumb1; ?> <?php echo $this->crumb2; ?> <?php echo $this->crumb3; ?> </div>
				<div id='language' class='span-3'>
					<form>
						<input type='image' name='language_ger' src='/flags/ger.png'>
						<input type='image' name='language_eng' src='/flags/eng.png'>
					</form>
				</div>
				<div>
					<div class='span-4'><a href='/front/warenkorb/index/'>
					<img src='/buttons/basket.png'> : <span id='shoppingCart'>
					<?php echo Zend_Registry::get('countShoppingCart'); ?></span> <?php echo translate('Programme'); ?></a></div>
				</div>
				<div class='span-5'>
					<a href="/front/password/index/"><?php echo translate('Passwort vergessen'); ?></a>
				</div>
			</div>

            <div id='reiter' class="span-23" style="border: #8a2be2 1px solid">
                <div id='info' class='span-5'>
                    &nbsp;
                </div>
                <div class="span-17">
                    <div class="span-5" style="background-color: #ffff00;"><a href='/front/login/index/'><?php echo translate('Programme'); ?></a></div>
                    <div class="span-5" style="background-color: #bc8f8f;"><a href='/front/hotelsearch/index/'><?php echo translate('Übernachtung'); ?></a></div>
                </div>
            </div>

			<div id='offers' class='span-23'>
				<?php echo $this->content; ?>
			</div>

			<div id='additional' class='span-23'>
				<?php echo Zend_Registry::get('debugModus'); ?>
			</div>
			<div id='bottom' class='span-23'>
				Impressum | <a href='/front/agb/index/'>AGB</a>
			</div>
		</div>
	</body>
</html>